INSERT INTO CATEGORY (CategoryID, CategoryName, Description) VALUES
(1, 'Tâm lý - Kỹ năng sống', 'Sách liên quan đến tâm lý và kỹ năng sống'),
(2, 'Khoa học', 'Sách liên quan đến khoa học'),
(3, 'Văn học', 'Sách liên quan đến văn học'),
(4, 'Sách thiếu nhi', 'Sách liên quan đến thiếu nhi'),
(5, 'Sách giáo khoa', 'Sách liên quan đến giáo khoa'),
(6, 'Ngoại ngữ', 'Sách liên quan đến ngoại ngữ'),
(7, 'Truyện tranh', 'Sách liên quan đến truyện tranh');

INSERT INTO AUTHOR (AuthorID, TenTacGia) VALUES
(1, 'Nguyễn Nhật Ánh'),
(2, 'Tô Hoài'),
(3, 'Ngô Tất Tố'),
(4, 'Trần Mình Hoàng'),
(5, 'Vũ Trọng Phụng'),
(6, 'Little Rainbow'),
(7, 'José Mauro de Vasconcelos'),
(8, 'Paulo Coelho'),
(9, 'Nguyễn Ngọc Tư'),
(10, 'Jeffrey Archer'),
(11, 'Châu Sa Đáy Mắt'),
(12, 'Huỳnh Thái Ngọc'),
(13, 'Gege Akutami'),
(14, 'Kim Khánh'),
(15, 'Phan Thị'),
(16, 'Nhiều Tác Giả'),
(17, 'Jim Collins'),
(18, 'T Harv Eker'),
(19, 'Napoleon Hill'),
(20, 'James Clear'),
(21, 'M. Scott Peck'),
(22, 'Hae Min'),
(23, 'Sơn Tùng'),
(24, 'Phùng Quán'),
(25, 'Audrey Bouquet'),
(26, 'Fabien Öckto Lambert');